In [1]:
!pip install torch 

  Using cached torch-2.12.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Using cached torch-2.12.0-cp313-cp313-win_amd64.whl (123.0 MB)



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import torch 
print(torch.__version__)

2.12.0+cpu


CREATING TENSORS 

In [3]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros(5,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
a=torch.ones(2,3)

In [9]:
print(a)
type(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Tensor

In [10]:
torch.rand(2,3)

tensor([[0.8187, 0.6805, 0.8704],
        [0.1533, 0.9041, 0.1850]])

In [11]:
torch.rand(2,3)

tensor([[0.6601, 0.1901, 0.1411],
        [0.4474, 0.4043, 0.4002]])

In [12]:
#manual_seed keeps the randomly assigned values same if anyone else runs it 
torch.manual_seed(123)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [13]:
torch.manual_seed(123)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [14]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [22]:
torch.linspace(0,10,6)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [29]:
x=torch.tensor([[7,8,9],[4,5,6]])

In [32]:
print(x)
x.dtype

tensor([[7, 8, 9],
        [4, 5, 6]])


torch.int64

In [33]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871]])

In [35]:
x.dtype

torch.int64

In [38]:
x=x.to(dtype=torch.float)

In [39]:
x.dtype

torch.float32

Mathematical Operation

In [40]:
x

tensor([[7., 8., 9.],
        [4., 5., 6.]])

In [41]:
x+2

tensor([[ 9., 10., 11.],
        [ 6.,  7.,  8.]])

In [43]:
x-3

tensor([[4., 5., 6.],
        [1., 2., 3.]])

In [44]:
x/3

tensor([[2.3333, 2.6667, 3.0000],
        [1.3333, 1.6667, 2.0000]])

In [45]:
x**2

tensor([[49., 64., 81.],
        [16., 25., 36.]])

In [48]:
(x*100)//2

tensor([[350., 400., 450.],
        [200., 250., 300.]])

In [49]:
((x*100)//2)%2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [54]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [55]:
a+b

tensor([[1.4000, 1.7794, 1.1380],
        [1.1245, 1.0399, 1.2718]])

In [56]:
a-b

tensor([[-0.4910,  0.1680, -0.2169],
        [-0.0928, -0.1959, -0.1146]])

In [57]:
a/b

tensor([[0.4807, 1.2084, 0.6798],
        [0.8476, 0.6830, 0.8347]])

In [58]:
a*b

tensor([[0.4298, 0.7846, 0.3120],
        [0.3140, 0.2608, 0.4011]])

In [59]:
a%b#mod operation 

tensor([[0.4545, 0.1680, 0.4606],
        [0.5159, 0.4220, 0.5786]])

In [60]:
a**b

tensor([[0.4745, 0.9788, 0.5914],
        [0.6684, 0.5868, 0.6844]])