In [1]:
!pip install torch 

  Using cached torch-2.12.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Using cached torch-2.12.0-cp313-cp313-win_amd64.whl (123.0 MB)



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import torch 
print(torch.__version__)

2.12.0+cpu


CREATING TENSORS 

In [3]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros(5,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
a=torch.ones(2,3)

In [9]:
print(a)
type(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Tensor

In [10]:
torch.rand(2,3)

tensor([[0.8187, 0.6805, 0.8704],
        [0.1533, 0.9041, 0.1850]])

In [11]:
torch.rand(2,3)

tensor([[0.6601, 0.1901, 0.1411],
        [0.4474, 0.4043, 0.4002]])

In [12]:
#manual_seed keeps the randomly assigned values same if anyone else runs it 
torch.manual_seed(123)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [13]:
torch.manual_seed(123)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [14]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [22]:
torch.linspace(0,10,6)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
torch.full((3,3)),(5)

TypeError: full() received an invalid combination of arguments - got (tuple), but expected one of:
 * (tuple of ints size, Number fill_value, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, Number fill_value, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
